# Generated by Django 5.0.5 on 2024-05-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='boy.jpg', null=True, upload_to='user_folder'),
        ),
    ]
